name: Compile Protobufs

on:
    push:
    workflow_dispatch:

jobs:
    protoc:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Build arrpc
              run: |
                  mkdir -p build
                  cd build
                  cmake ../arrpc
                  make -j$(nproc)
